# Generated by Django 5.1.7 on 2025-05-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['is_active'], name='core_master_is_acti_662e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['experience'], name='core_master_experie_524e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_name'], name='core_order_client__3038eb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone'], name='core_order_phone_582566_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='core_order_status_6fe5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_created'], name='core_order_date_cr_d2e958_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'appointment_date'], name='status_appointment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_name', 'phone'], name='client_name_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='core_review_rating_41e437_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_published'], name='core_review_is_publ_f740cd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['master', 'rating'], name='master_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price'], name='core_servic_price_72c8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_popular'], name='core_servic_is_popu_7bf01a_idx'),
        ),
    ]
