# Generated by Django 5.1.7 on 2025-06-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_master_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=60, help_text='Время выполнения в минутах', verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(blank=True, default=False, verbose_name='Популярная услуга'),
        ),
    ]
